# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /source

# copy everything else and build app
COPY diff.Api/. ./diff.Api/
COPY diff.Core/. ./diff.Core/
COPY NetCash/. ./NetCash/
WORKDIR /source/diff.Api
ENTRYPOINT [ "dotnet", "run" ]